class WelcomeController < ApplicationController
    #this file was generated by running the command:
    # rails g controller welcome

    #Inside of a controller, every method is called an "action"
    
    def index
        #by default rails will render a template within views
        #under views/welcome (it will match the controller name)
        #this action will render out the file views/welcome/index.html.erb
    end

     #views/welcome/goodbye.html.erb
    def goodbye
    end

    def form_example
    end

end
